#trigger:
#- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_rsa.pub'
- task: DownloadSecureFile@1
  name: privatekey
  inputs:
    secureFile: 'id_rsa'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      ls -lart  /home/vsts/work/1/s
      echo "*********************************************"
      ls -lart /home/vsts/work/1/
      ls -lart $(Agent.TempDirectory)
      
      echo "*********************************************"
      echo $(Agent.TempDirectory)
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azure'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'DefaultResourceGroup-EUS'
    backendAzureRmResourceGroupLocation: 'east us'
    backendAzureRmStorageAccountName: 'shastorage'
    backendAzureRmContainerName: 'tfdemo'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'forceunlock'
    allowTelemetryCollection: false
    lockID: 'ef4983ac-c60a-aa33-16c0-473c52739d13'
- task: TerraformCLI@0
  inputs:
    command: 'apply'
    environmentServiceName: 'azure'
    commandOptions:  '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath) -var private=$(privatekey.secureFilePath)'
    allowTelemetryCollection: false