#trigger:
#- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo K8S Terraform Azure!
  displayName: 'Run a one-line script'
- task: DownloadSecureFile@1
  name: publickey
  inputs:
    secureFile: 'id_rsa.pub'
- task: DownloadSecureFile@1
  name: privatekey
  inputs:
    secureFile: 'id_rsa'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: 'ls -lart  /home/vsts/work/1/s'
- task: TerraformCLI@0
  inputs:
    command: 'init'
    backendType: 'azurerm'
    backendServiceArm: 'azure'
    ensureBackend: true
    backendAzureRmResourceGroupName: 'DefaultResourceGroup-EUS'
    backendAzureRmResourceGroupLocation: 'east us'
    backendAzureRmStorageAccountName: 'shastorage'
    backendAzureRmContainerName: 'tfdemo'
    backendAzureRmKey: 'terraform.tfstate'
    allowTelemetryCollection: false
- task: TerraformCLI@0
  inputs:
    command: 'plan'
    environmentServiceName: 'azure'
    commandOptions: '-var client_id=$(client_id) -var client_secret=$(client_secret) -var ssh_public_key=$(publickey.secureFilePath) -var private=$(privatekey.secureFilePath)'
    allowTelemetryCollection: false